default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password

development:
  <<: *default
  database: crownstack_development

test:
  <<: *default
  database: crownstack_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: crownstack_production
